In [1]:
from keras.layers import SimpleRNN
from keras.layers import LSTM
from keras.models import Sequential
from keras.layers import Embedding,SimpleRNN
from keras.datasets import imdb
from keras.preprocessing import sequence
from keras.layers import Dense
import numpy as np
import sys
sys.path.append("/data/keras/npl/")
from baidunpl import BaiduNpl

Using TensorFlow backend.


In [2]:
client=BaiduNpl()
model = Sequential()
model.add(LSTM(32))
# model.add(Dense(1, activation='sigmoid'))
model.add(Dense(64,activation='relu'))
model.add(Dense(5,activation='softmax'))
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['acc'])

input_train=["后天天气如何","明天天气如何","下周一的天气",
             "我要去江门","我要去北京故宫的中心","导航到广州长隆",
             "我想听张韶涵的歌","来一首张学友的歌","我想听卓依婷的歌",
             "六点提醒我开会","五分钟后提醒睡觉","下午两点提醒我上学",
             "感冒了吃什么药","发烧了怎么办","眼睛不舒服怎么处理"]
y_train=np.array([[1,0,0,0,0],[1,0,0,0,0],[1,0,0,0,0],#问天气
                  [0,1,0,0,0],[0,1,0,0,0],[0,1,0,0,0],#导航
                  [0,0,1,0,0],[0,0,1,0,0],[0,0,1,0,0],#唱歌
                  [0,0,0,1,0],[0,0,0,1,0],[0,0,0,1,0],#提醒功能
                  [0,0,0,0,1],[0,0,0,0,1],[0,0,0,0,1]#医疗咨询
                 ])
input_train2=[]
for one_train in input_train:
    vecs=client.getVecFromJuzi(one_train)
    input_train2.append(vecs)
input_train2=np.array(input_train2)

input_train2=sequence.pad_sequences(input_train2,dtype="float",maxlen=10,padding='post',truncating='post',)
print(input_train2.shape)
history = model.fit(input_train2, y_train,epochs=15,batch_size=5)

(15, 10, 1024)
Epoch 1/15
15/15 [==============================] - 1s 83ms/step - loss: 1.5857 - acc: 0.4000
Epoch 2/15
15/15 [==============================] - 0s 4ms/step - loss: 1.3877 - acc: 0.8667
Epoch 3/15
15/15 [==============================] - 0s 4ms/step - loss: 1.2120 - acc: 0.8000
Epoch 4/15
15/15 [==============================] - 0s 4ms/step - loss: 1.0343 - acc: 0.9333
Epoch 5/15
15/15 [==============================] - 0s 4ms/step - loss: 0.8824 - acc: 0.9333
Epoch 6/15
15/15 [==============================] - 0s 4ms/step - loss: 0.7776 - acc: 1.0000
Epoch 7/15
15/15 [==============================] - 0s 4ms/step - loss: 0.6802 - acc: 0.9333
Epoch 8/15
15/15 [==============================] - 0s 4ms/step - loss: 0.6020 - acc: 0.9333
Epoch 9/15
15/15 [==============================] - 0s 4ms/step - loss: 0.5404 - acc: 1.0000
Epoch 10/15
15/15 [==============================] - 0s 4ms/step - loss: 0.4745 - acc: 1.0000
Epoch 11/15
15/15 [==============================] - 

In [5]:
tests=["星期二天气","导航到动物园","我想听周杰伦的歌","五点提醒我","得了结膜炎怎么处理"]
vecs2=[]
for test in tests: 
    vecs=client.getVecFromJuzi(test)  
    vecs2.append(vecs)
vecs=np.array(vecs2)
vecs2=sequence.pad_sequences(vecs2,dtype="float",maxlen=10,padding='post',truncating='post',)
preds = model.predict(vecs2)
print(preds)

[[0.8672072  0.01300291 0.04431497 0.01018356 0.06529141]
 [0.01103215 0.60931677 0.02526247 0.29438505 0.06000359]
 [0.06556533 0.05582128 0.67360616 0.17635721 0.02865007]
 [0.01030163 0.23318847 0.06211161 0.6547908  0.0396075 ]
 [0.03270157 0.01632417 0.00789019 0.00804777 0.9350363 ]]
